spring.application.name=MyNutRest
spring.datasource.url=jdbc:mysql://localhost:3306/mynut
spring.datasource.username=bob
spring.datasource.password=bob
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.ai.mcp.server.name=MyNutRest
spring.ai.mcp.server.version=1.0.0
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.type=sync
